services:
  spider-tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8009:8009"
    networks:
      - spider-vpn-network
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    restart: always

networks:
  spider-vpn-network:
    external: true
