version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: host
    ports:
      - "8009:8009"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    command: bash -c "pip install watchdog && watchmedo auto-restart --recursive --patterns='*.py' -- python main.py"

